apiVersion: v2
name: fulcio
description: |
  Fulcio is a free code signing Certificate Authority, built to make short-lived certificates available to anyone.

type: application

version: 2.5.1
appVersion: 1.6.1

keywords:
  - security
  - pki

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

dependencies:
  - name: ctlog
    version: 0.2.55
    repository: https://sigstore.github.io/helm-charts
    condition: ctlog.enabled

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: fulcio
      image: gcr.io/projectsigstore/fulcio:v1.6.1@sha256:e2d3b127fc3fa6c23ce625e99a8435d546dd16ae2528e81b648fc9fcd1360a18
    - name: createcerts
      image: ghcr.io/sigstore/scaffolding/createcerts:v0.7.5@sha256:cd605e02eef0c0d70aa0b4805c6483054ab652f8ff0e9b382f06961596ef3e73
